### ISSUE TITLE
AWS support for CI runners

### ISSUE THREAD

**Issue by tcarmet** [scality/runner-manager#164]
Introduce in the [runner-manager](https://github.com/scality/runner-manager) the capability to spawn AWS EC2 instances.

## Getting started

Get familiar with the project and check the existant documentation: https://scality.github.io/runner-manager/

Look for getting started guides and how to add a new [cloud provider](https://scality.github.io/runner-manager/setup/clouds/#supporting-a-new-cloud-provider)

## AWS runners

The goal will be to be able to configure runner pools on aws, the runner should support in its configuration.

```[tasklist]
### Tasks
- [x] Define how the configuration on the runner will look like
- [x] Review and get the configuration specs approved
- [x] Develop the AWS support
```

**Comment by gaspardmoindrot** [comment]
How the configuration of a runner with AWS will look like :

1. Create an EC2 instance (or use an existant one)
2. SSH the EC2 instance
3. Go to the project > Settings > Actions > Runners, click "New self-hosted runner" and set it up according to your convenience
4. Install the runner on the EC2 following the instructions
5. Set your workflow with the option "New workflow" on Github Action page or via a yaml file on the repo /.github/workflows/
