### ISSUE TITLE
Runner manager security vulnerability

### ISSUE THREAD

**Issue by tcarmet** [scality/runner-manager#200]
Try to fix the CRITICAL and HIGH security issues

```[tasklist]
### Tasks
- https://github.com/scality/runner-manager/issues/216
- https://github.com/scality/runner-manager/issues/217
- https://github.com/scality/runner-manager/issues/218
- [ ] https://github.com/scality/runner-manager/issues/216
- [ ] https://github.com/scality/runner-manager/issues/217
- [ ] https://github.com/scality/runner-manager/issues/218
```

**Comment by gaspardmoindrot** [comment]
* https://github.com/scality/runner-manager/issues/216
* https://github.com/scality/runner-manager/issues/217
* https://github.com/scality/runner-manager/issues/218
